ci: nix flake show comment in prs
ngi-nix/ngipkgs pull request #114
Opened 2023-11-29 12:42 UTC by mightyiam

2023-11-29 14:04 UTC, lorenzleutgeb requested changes
I'd like to avoid installing packages via `apt`, because we're into Nix.

2023-11-29 14:04 UTC, lorenzleutgeb commented on .github/workflows/pull_request.yaml
> +          echo 'EOF' >> $GITHUB_OUTPUT
```suggestion
          echo 'output <<EOF' >> $GITHUB_OUTPUT
          nix flake show --all-systems | nix run nixpkgs#ansifilter >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
```

Not sure whether the reference to Nixpkgs will work like that...

2023-11-29 14:50 UTC, lorenzleutgeb commented
What'd be even cooler, IMO, would be to show the differences.

What works quite nicely on my machine:
```shell
$ export REF=refs/heads/main
$ delta \
  <(nix flake show ".?ref=$REF&rev=$(git rev-parse $REF)" | nix run nixpkgs#ansifilter) \
  <(nix flake show | nix run nixpkgs#ansifilter)
```

So, for GitHub Actions we'd probably need:

```shell
diff -u \
  <(nix flake show ".?ref=$GITHUB_REF&rev=$(git rev-parse $GITHUB_REF)" | nix run nixpkgs#ansifilter) \
  <(nix flake show | nix run nixpkgs#ansifilter)
```

And then use

``````
```patch
${{ steps.flake-show.outputs.output }}
```
``````

2023-11-29 15:47 UTC, mightyiam commented
That would be nice. Perhaps a full-context diff?

2023-12-05 19:37 UTC, lorenzleutgeb approved these changes

2023-12-05 19:45 UTC, merged

2023-12-05 19:45 UTC, mightyiam commented
Thank you, @lorenzleutgeb .