naja: init at 0-unstable-2024-07-21
ngi-nix/ngipkgs pull request #323
Opened 2024-07-27 11:10 UTC by eljamm

Also opened in https://github.com/NixOS/nixpkgs/pull/330385

Closes #321

2024-07-30 16:44 UTC, OPNA2608 requested changes

2024-07-30 16:44 UTC, OPNA2608 commented on pkgs/by-name/libdwarf-lite/package.nix
> +    "-DBUILD_DWARFDUMP=FALSE"
```suggestion
    (lib.cmakeBool "PIC_ALWAYS" true)
    (lib.cmakeBool "BUILD_DWARFDUMP" false)
```

2024-07-30 16:44 UTC, OPNA2608 commented on pkgs/by-name/naja/package.nix
> +    "-DCPPTRACE_USE_EXTERNAL_ZSTD=ON"
```suggestion
    (lib.cmakeBool "CPPTRACE_USE_EXTERNAL_LIBDWARF" true)
    (lib.cmakeBool "CPPTRACE_USE_EXTERNAL_ZSTD=ON" true)
```

2024-07-30 16:44 UTC, OPNA2608 commented on pkgs/by-name/naja/package.nix
> +  ];
This'll break with `strictDeps`… and when our CMake gets patched to treat `nativeBuildInputs` and `buildInputs` `PATH` separation better: https://github.com/NixOS/nixpkgs/pull/318226

```suggestion
  nativeBuildInputs = [
    bison
    capnproto
    cmake
    doxygen
    flex
    pkg-config
    (python3.withPackages (ps: with ps; [
      sphinx
    ])) 
  ];

  buildInputs = [
    boost
    flex # include dir
    libdwarf-lite
    openssl # capnproto
    tbb_2021_11
    zlib # capnproto
    zstd
  ];
```

Only unsure about if `capnproto` should also be in `buildInputs` for its CMake modules.

2024-07-30 16:44 UTC, OPNA2608 commented on pkgs/by-name/naja/package.nix
> +  zstd,
```suggestion
  libdwarf-lite,
  openssl,
  pkg-config,
  python3,
  tbb_2021_11,
  zlib,
  zstd,
```

2024-07-30 20:55 UTC, eljamm commented
@OPNA2608 The package compiles fine with just `python3`, so I just used that instead of `(python3.withPackages (ps: with ps; [ sphinx ]))`.

I don't know why it didn't work for you, though. Can you still reproduce that?

2024-08-01 11:11 UTC, fricklerhandwerk approved these changes

2024-08-01 11:13 UTC, merged