Change formatting to rfc style
ngi-nix/ngipkgs pull request #447
Opened 2024-11-27 03:04 UTC by jasonodoom

These changes bake a full-reformat commit and exclude that from blame.

In addition, the `alejandra` hook in `flakes.nix` is replaced with `nixfmt-rfc-style`. The hash from `nix fmt` formatting changes in `.git-blame-ignore-revs` is replaced with the hash from formatting changes from`nixfmt-rfc-style`.

2024-11-28 17:20 UTC, lorenzleutgeb requested changes, later dismissed

2024-11-28 17:20 UTC, lorenzleutgeb commented on .git-blame-ignore-revs
You should not remove the old hash and comment, but rather append your new hash and comment to this file so that _both_ formatting commits are ignored. Just because you do another reformatting, that does not mean that the older reformatting now somehow gets relevant again.

2024-12-01 21:53 UTC, jasonodoom commented on .git-blame-ignore-revs
> Just because you do another reformatting, that does not mean that the older reformatting now somehow gets relevant again.

Aah, that was my understanding initially. Thanks for the clarification. Please see: [8166d9f](https://github.com/ngi-nix/ngipkgs/pull/447/commits/8166d9f7e779eb7a1dc876e82d0170ba2ebecfb6)

2024-12-01 22:45 UTC, wegank commented
Merge conflict, please rebase.

2024-12-02 14:14 UTC, wegank commented
Merge conflict again...

2024-12-02 14:22 UTC, fricklerhandwerk commented
Oh this won't be any fun as long as we keep working on `main`... :)

2024-12-03 01:43 UTC, jasonodoom commented
@wegank thanks :)

2024-12-03 08:50 UTC, fricklerhandwerk commented
Nice, thanks a lot @jasonodoom!

2024-12-03 13:13 UTC, fricklerhandwerk approved these changes

2024-12-03 13:13 UTC, merged